apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-vcl
  namespace: {{.Release.Namespace}}
data:
{{ if eq .Values.ROCKETSHIP_PROJECT_ENVIRONMENT "dev" }}
  {{- range $path, $d := .Files.Glob "etc/varnish/default-dev.vcl" }}
  default.vcl: |-
  {{- $d | toString | nindent 4 }}
  {{ end }}
{{ else if eq .Values.ROCKETSHIP_PROJECT_ENVIRONMENT "tst" }}
  {{- range $path, $d := .Files.Glob "etc/varnish/default-tst.vcl" }}
  default.vcl: |-
  {{- $d | toString | nindent 4 }}
  {{ end }}
{{ else if eq .Values.ROCKETSHIP_PROJECT_ENVIRONMENT "test" }}
  {{- range $path, $d := .Files.Glob "etc/varnish/default-tst.vcl" }}
  default.vcl: |-
  {{- $d | toString | nindent 4 }}
  {{ end }}
{{ else if eq .Values.ROCKETSHIP_PROJECT_ENVIRONMENT "acc" }}
  {{- range $path, $d := .Files.Glob "etc/varnish/default-acc.vcl" }}
  default.vcl: |-
  {{- $d | toString | nindent 4 }}
  {{ end }}
{{ else if eq .Values.ROCKETSHIP_PROJECT_ENVIRONMENT "accept" }}
  {{- range $path, $d := .Files.Glob "etc/varnish/default-acc.vcl" }}
  default.vcl: |-
  {{- $d | toString | nindent 4 }}
  {{ end }}
{{ else if eq .Values.ROCKETSHIP_PROJECT_ENVIRONMENT "production" }}
  {{- range $path, $d := .Files.Glob "etc/varnish/default-prd.vcl" }}
  default.vcl: |-
  {{- $d | toString | nindent 4 }}
  {{ end }}
{{ else if eq .Values.ROCKETSHIP_PROJECT_ENVIRONMENT "prd" }}
  {{- range $path, $d := .Files.Glob "etc/varnish/default-prd.vcl" }}
  default.vcl: |-
  {{- $d | toString | nindent 4 }}
  {{ end }}
{{ else }}
  {{- range $path, $d := .Files.Glob "etc/varnish/default.vcl" }}
  default.vcl: |-
  {{- $d | toString | nindent 4 }}
  {{ end }}
{{ end }}

