---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-maintenance
  namespace: {{.Release.Namespace}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    loki: {{.Values.division }}-{{.Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-maintenance
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-maintenance
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        loki: {{.Release.Namespace}}   
      annotations:
        date: "+%H:%M:%S %d/%m/%y"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: maintenance
          image: ghcr.io/organisation/maintenance:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONTACT_LINK
              value: {{ .Values.maintenance.contactlink }}
            - name: MESSAGE
              value: {{ .Values.maintenance.message }}
            - name: RESPONSE_CODE
              value: "521 Webserver Is Down"
            - name: THEME
              value: "Light"
            - name: LINK_COLOR
              value: {{ .Values.maintenance.linkcolor }}
            - name: MAIL_ADDRESS
              value: {{ .Values.maintenance.emailaddress }}
            - name: TITLE
              value: {{ .Values.maintenance.title }}
            - name: TEAM_NAME
              value: {{ .Values.maintenance.teamname }}
            - name: HEADLINE
              value: {{ .Values.maintenance.headline }}
            - name: PORT
              value: "80"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
