---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-drush-pod
  namespace: {{.Release.Namespace}}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
    loki: {{.Values.division }}-{{.Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-drush-pod
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-drush-pod
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
        loki: {{.Values.division }}-{{.Values.environment }}
      annotations:
        date: "+%H:%M:%S %d/%m/%y"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{ include "drupal.volumes" . | nindent 9 }}

      containers:
        - name: php-fpm
          image: {{.Values.php_image_name }}:{{ .Values.image.version }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ include "drupal.envvars" . | nindent 13 }}
          volumeMounts:
            {{ include "drupal.mounts" . | nindent 13 }}           
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources: 
            requests: 
              cpu: 100m
              memory: "256Mi"
            limits:   
              cpu: {{ .Values.resources.php.cpu }}
              memory: {{ .Values.resources.php.mem }}
              
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
