apiVersion: v1
kind: Secret
metadata:
  name: ghcrimpagepullsecret
  namespace: {{.Release.Namespace}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}