apiVersion: v1
kind: Pod
metadata:
  name: "{{.Release.Name}}-drush-pod"
  namespace: {{.Release.Namespace}}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    loki: {{.Values.division }}-{{.Values.environment }}
spec:
  {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    volumes:
      {{ include "drupal.volumes" . | nindent 7 }}

    containers:
      - name: php-fpm
        image: {{.Values.php_image_name }}:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        {{ include "drupal.mounts" . | nindent 9 }}
        env:
          {{ include "drupal.envvars" . | nindent 11 }}
        resources: 
          requests: 
            cpu: 20m
            memory: "256Mi"
          limits:   
            cpu: 2
            memory: "4112Mi"

      - name: php-fpm-exporter
        image: hipages/php-fpm_exporter
        ports:
        - containerPort: 9253
          protocol: TCP
          name: php-fpm-metrics
        resources: 
          {{ include "drupal.exporter.resources" . | nindent 11 }}
