---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: {{.Release.Name}}
  resources:
    requests:
      storage: 5Gi
      