---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: {{.Release.Namespace}}
  labels:
    component: memcached
spec:
  ports:
  - name: memcached
    port: 11211
    targetPort: 11211
  - port: 9150
    targetPort: 9150
    protocol: TCP
    name: metrics
  selector:
    app: {{.Release.Name}}-memcached