---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{.Release.Namespace}}
  labels:
    component: nginx
spec:
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
      name: nginx
    - port: 9113
      targetPort: 9113
      protocol: TCP
      name: metrics
  selector:
    app: {{.Release.Name}}-nginx
