---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  namespace: {{.Release.Namespace}}
  labels:
    component: php-fpm
spec:
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: php-fpm
    - port: 9253
      targetPort: 9253
      protocol: TCP
      name: php-fpm-exporter
  selector:
    app: {{.Release.Name}}-php-fpm
