---
apiVersion: v1
kind: Service
metadata:
  name: maintenance
  namespace: {{.Release.Namespace}}
  labels:
    component: maintenance
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: maintenance
  selector:
    app: {{.Release.Name}}-maintenance
